---
- hosts: all
  become: true
  gather_facts: true
  tasks:
    - name: Refresh apt cache on Debian/Ubuntu
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600
      when: ansible_facts['os_family'] == 'Debian'

    - name: Install Apache and PHP using correct backend
      ansible.builtin.package:
        name:
          - "{{ apache_package }}"
          - "{{ php_package }}"
        state: latest
        use: "{{ 'dnf' if ansible_facts['os_family'] == 'RedHat' else 'apt' }}"

